//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMPM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VIRGILIOEntities : DbContext
    {
        public VIRGILIOEntities()
            : base("name=VIRGILIOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Personas> Personas { get; set; }
    
        public virtual int INGRESAR_CLINETES(string nOMBRE, string aPELLIDO, string dIRECCION)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOParameter = aPELLIDO != null ?
                new ObjectParameter("APELLIDO", aPELLIDO) :
                new ObjectParameter("APELLIDO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_CLINETES", nOMBREParameter, aPELLIDOParameter, dIRECCIONParameter);
        }
    
        public virtual int UPDATE_CLINETES(string nOMBRE, string aPELLIDO, string cEDULA, string dIRECCION, Nullable<int> iD)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOParameter = aPELLIDO != null ?
                new ObjectParameter("APELLIDO", aPELLIDO) :
                new ObjectParameter("APELLIDO", typeof(string));
    
            var cEDULAParameter = cEDULA != null ?
                new ObjectParameter("CEDULA", cEDULA) :
                new ObjectParameter("CEDULA", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_CLINETES", nOMBREParameter, aPELLIDOParameter, cEDULAParameter, dIRECCIONParameter, iDParameter);
        }
    
        public virtual ObjectResult<Filtro_Usuario_Result> Filtro_Usuario(Nullable<int> offsetValue, Nullable<int> pagingSize)
        {
            var offsetValueParameter = offsetValue.HasValue ?
                new ObjectParameter("OffsetValue", offsetValue) :
                new ObjectParameter("OffsetValue", typeof(int));
    
            var pagingSizeParameter = pagingSize.HasValue ?
                new ObjectParameter("PagingSize", pagingSize) :
                new ObjectParameter("PagingSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Filtro_Usuario_Result>("Filtro_Usuario", offsetValueParameter, pagingSizeParameter);
        }
    }
}
